name: Deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: pnpm build

      - name: Create updated web.config
        run: |
          cat > web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <webSocket enabled="false" />
              <handlers>
                <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
              </handlers>
              <rewrite>
                <rules>
                  <rule name="DynamicContent">
                    <match url="/*" />
                    <action type="Rewrite" url="server.js" />
                  </rule>
                </rules>
              </rewrite>
              <security>
                <requestFiltering removeServerHeader="true" />
              </security>
              <httpProtocol>
                <customHeaders>
                  <remove name="X-Powered-By" />
                </customHeaders>
              </httpProtocol>
              <iisnode 
                nodeProcessCommandLine="%ProgramFiles%\nodejs\node.exe"
                loggingEnabled="true"
                logDirectory="iisnode"
                debuggingEnabled="true"
                devErrorsEnabled="true"
              />
            </system.webServer>
          </configuration>
          EOL

      - name: Create server.js
        run: |
          cat > server.js << 'EOL'
          // server.js
          const { createServer } = require('http');
          const { parse } = require('url');
          const next = require('next');

          const dev = process.env.NODE_ENV !== 'production';
          const hostname = '0.0.0.0';
          const port = process.env.PORT || 3000;

          // Create the Next.js app
          const app = next({ 
            dev,
            dir: __dirname
          });

          const handle = app.getRequestHandler();

          app.prepare()
            .then(() => {
              createServer(async (req, res) => {
                try {
                  // Parse request URL
                  const parsedUrl = parse(req.url, true);
                  
                  // Let Next.js handle the request
                  await handle(req, res, parsedUrl);
                } catch (err) {
                  console.error('Error occurred handling request:', err);
                  res.statusCode = 500;
                  res.end('Internal Server Error');
                }
              })
              .listen(port, hostname, (err) => {
                if (err) throw err;
                console.log(`> Ready on http://${hostname}:${port}`);
              });
            })
            .catch((err) => {
              console.error('Failed to prepare Next.js app:', err);
              process.exit(1);
            });
          EOL

      - name: Prepare deployment package
        run: |
          mkdir -p deploy

          # Use standalone output if available
          if [ -d ".next/standalone" ]; then
            echo "Using standalone output"
            cp -r .next/standalone/* deploy/
            
            # Ensure static files are correctly copied
            mkdir -p deploy/.next/static
            cp -r .next/static deploy/.next/
          else
            echo "Standalone output not found, using regular build"
            # Copy minimum required files for a regular Next.js app
            cp -r .next deploy/
            cp package.json deploy/
            
            # Add production dependencies only
            cd deploy
            echo "Installing production dependencies"
            pnpm install --prod
            cd ..
          fi

          # Copy public directory if it exists
          if [ -d "public" ]; then
            cp -r public deploy/
          fi

          # Copy config files
          cp next.config.js deploy/ || echo "next.config.js not found, creating minimal version"
          if [ ! -f "deploy/next.config.js" ]; then
            echo "module.exports = { output: 'standalone' };" > deploy/next.config.js
          fi

          # Copy server files
          cp server.js web.config deploy/

          # Create zip file
          cd deploy && zip -r ../app.zip . && cd ..

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ammban-frontend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
