name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "ammban-frontend"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./.next/standalone

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: "Production"
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: app
        - name: "Deploy to Azure Web App"
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: ${{ env.WEBAPP_NAME }}
            slot-name: "Production"
            publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
            package: ./build/standalone
